### ISSUE TITLE
IBC forwarding

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/cosmos-gravity-bridge#309]
Depends on issue #301 for testing.

This issue is an Epic about creating an Ethereum -> IBC -> Cosmos flow that is capable of both sending funds to and from Ethereum and a destination IBC chain without requiring any direct interaction with the Gravity host chain.

- [ ] Modify SendToCosmos to take Bech32 prefix
- [ ] Modify event parsing code
- [ ] Import ICS20 prefix lookup module
- [ ] Use module lookup to forward non-local denoms
- [ ] Create integration test hooking to #301 
- [ ] Create message type for a remote withdraw to Ethereum via ibc
- [ ] Add above to integration test
